Add files via upload
C:\Users\Brian Marcks\Desktop\LAB>git push origin master
To https://github.com/Rich-Brian/Lab-One.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Rich-Brian/Lab-One.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.